//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Narail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int id { get; set; }
        public string Header { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Contents { get; set; }
        public string Tags { get; set; }
        public string Subject { get; set; }
        public Nullable<int> Writer { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedBy { get; set; }
        public string Image { get; set; }
        public string Active { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<int> Category { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual NewsCategory NewsCategory { get; set; }
    }
}
