//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Narail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public int id { get; set; }
        public string SiteHeader { get; set; }
        public string SiteDescription { get; set; }
        public string SiteAcces { get; set; }
        public string ContactAdress { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string AboutText { get; set; }
        public string AboutImage { get; set; }
        public string FacebookLink { get; set; }
        public string TwitterLink { get; set; }
        public string InstagramLink { get; set; }
        public string Linledin { get; set; }
        public string YoutubeLink { get; set; }
        public string YoutubeLiveLink { get; set; }
        public string CompanyLogo { get; set; }
        public string CompanyName { get; set; }
        public string CompanySlogan { get; set; }
        public string FounderName1 { get; set; }
        public string FounderImage1 { get; set; }
        public string FounderName2 { get; set; }
        public string FounderImage2 { get; set; }
        public string Seo { get; set; }
    }
}
